### ISSUE TITLE
ReferenceError: L is not defined

### ISSUE THREAD

**Issue by emcniece** [angular-ui/ui-leaflet#204]
Using https://github.com/AngularClass/NG6-starter - created a new component, added the leaflet directive to the component directive template.

    ReferenceError: L is not defined
    at _getDefaults (http://localhost:3000/bundle.js:36242:19)
    at Object.setDefaults (http://localhost:3000/bundle.js:36319:32)
    at link (http://localhost:3000/bundle.js:34186:49)
    at http://localhost:3000/bundle.js:8925:45
    at invokeLinkFn (http://localhost:3000/bundle.js:8931:10)
    at nodeLinkFn (http://localhost:3000/bundle.js:8425:12)
    at compositeLinkFn (http://localhost:3000/bundle.js:7821:14)
    at compositeLinkFn (http://localhost:3000/bundle.js:7824:14)
    at nodeLinkFn (http://localhost:3000/bundle.js:8420:25)
    at compositeLinkFn (http://localhost:3000/bundle.js:7821:14) <div class="angular-leaflet-map ng-isolate-scope" defaults="defaults" lf-center="center" height="480px" width="640px">

Suspect race condition or init order mishap. Full commit: https://github.com/emcniece/holiday-house-tour/commit/42994e0f37efcd7baade2d296d2eaf29ab0e9d32

Notable files:

* [client/app/common/map/map.js](https://github.com/emcniece/holiday-house-tour/blob/master/client/app/common/map/map.js)
* [client/app/common/map/map.html](https://github.com/emcniece/holiday-house-tour/blob/master/client/app/common/map/map.html)
* [client/app/common/map/map.controller.js](https://github.com/emcniece/holiday-house-tour/blob/master/client/app/common/map/map.controller.js)
* [client/app/common/map/map.component.js](https://github.com/emcniece/holiday-house-tour/blob/master/client/app/common/map/map.component.js)

Am I doing something terribly wrong in initializing this directive? Thanks for your time.

**Comment by emcniece** [comment]
Resolved - needed to include leaflet.js `<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>` in the head.
